# Generated by Django 5.0.3 on 2024-04-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_remove_client_user_ptr_delete_agent_delete_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='spotsAvailable',
            new_name='freeSpots',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='destination',
            name='sale',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
