# Generated by Django 5.0.3 on 2024-04-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='freeSpots',
            new_name='totalSpots',
        ),
    ]
