# Generated by Django 5.0.3 on 2024-04-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_rename_freespots_destination_totalspots'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='freeSpots',
            field=models.IntegerField(default=models.F('totalSpots')),
            preserve_default=False,
        ),
    ]
