# Generated by Django 5.0.3 on 2024-04-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_destination_freespots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='freeSpots',
        ),
    ]
